# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_demo_1.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(834, 597)
        Form.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.formGroupBox = QtWidgets.QGroupBox(Form)
        self.formGroupBox.setGeometry(QtCore.QRect(20, 20, 161, 295))
        self.formGroupBox.setObjectName("formGroupBox")
        self.formLayout = QtWidgets.QFormLayout(self.formGroupBox)
        self.formLayout.setObjectName("formLayout")
        self.s1__lb_1 = QtWidgets.QLabel(self.formGroupBox)
        self.s1__lb_1.setObjectName("s1__lb_1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.s1__lb_1)
        self.s1__box_1 = QtWidgets.QPushButton(self.formGroupBox)
        self.s1__box_1.setAutoRepeatInterval(100)
        self.s1__box_1.setDefault(True)
        self.s1__box_1.setObjectName("s1__box_1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.s1__box_1)
        self.s1__lb_2 = QtWidgets.QLabel(self.formGroupBox)
        self.s1__lb_2.setObjectName("s1__lb_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.s1__lb_2)
        self.s1__box_2 = QtWidgets.QComboBox(self.formGroupBox)
        self.s1__box_2.setObjectName("s1__box_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.s1__box_2)
        self.s1__lb_3 = QtWidgets.QLabel(self.formGroupBox)
        self.s1__lb_3.setObjectName("s1__lb_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.s1__lb_3)
        self.s1__box_3 = QtWidgets.QComboBox(self.formGroupBox)
        self.s1__box_3.setObjectName("s1__box_3")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.s1__box_3)
        self.s1__lb_4 = QtWidgets.QLabel(self.formGroupBox)
        self.s1__lb_4.setObjectName("s1__lb_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.s1__lb_4)
        self.s1__box_4 = QtWidgets.QComboBox(self.formGroupBox)
        self.s1__box_4.setObjectName("s1__box_4")
        self.s1__box_4.addItem("")
        self.s1__box_4.addItem("")
        self.s1__box_4.addItem("")
        self.s1__box_4.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.s1__box_4)
        self.s1__lb_5 = QtWidgets.QLabel(self.formGroupBox)
        self.s1__lb_5.setObjectName("s1__lb_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.s1__lb_5)
        self.s1__box_5 = QtWidgets.QComboBox(self.formGroupBox)
        self.s1__box_5.setObjectName("s1__box_5")
        self.s1__box_5.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.s1__box_5)
        self.s1__lb_6 = QtWidgets.QLabel(self.formGroupBox)
        self.s1__lb_6.setObjectName("s1__lb_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.s1__lb_6)
        self.s1__box_6 = QtWidgets.QComboBox(self.formGroupBox)
        self.s1__box_6.setObjectName("s1__box_6")
        self.s1__box_6.addItem("")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.s1__box_6)
        self.open_button = QtWidgets.QPushButton(self.formGroupBox)
        self.open_button.setObjectName("open_button")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.open_button)
        self.close_button = QtWidgets.QPushButton(self.formGroupBox)
        self.close_button.setObjectName("close_button")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.close_button)
        self.label = QtWidgets.QLabel(self.formGroupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.formGroupBox)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_2 = QtWidgets.QLabel(self.formGroupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.formGroupBox)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.btn_connect_device = QtWidgets.QPushButton(self.formGroupBox)
        self.btn_connect_device.setObjectName("btn_connect_device")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.btn_connect_device)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(190, 10, 631, 571))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 30, 401, 171))
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 14, 382, 151))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_modbus_addr = QtWidgets.QLabel(self.layoutWidget)
        self.label_modbus_addr.setObjectName("label_modbus_addr")
        self.horizontalLayout_8.addWidget(self.label_modbus_addr)
        self.spinBox_modbus_addr = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_modbus_addr.setProperty("value", 1)
        self.spinBox_modbus_addr.setObjectName("spinBox_modbus_addr")
        self.horizontalLayout_8.addWidget(self.spinBox_modbus_addr)
        self.label_device_ID = QtWidgets.QLabel(self.layoutWidget)
        self.label_device_ID.setObjectName("label_device_ID")
        self.horizontalLayout_8.addWidget(self.label_device_ID)
        self.comboBox_device_ID = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_device_ID.setObjectName("comboBox_device_ID")
        self.comboBox_device_ID.addItem("")
        self.comboBox_device_ID.addItem("")
        self.comboBox_device_ID.addItem("")
        self.comboBox_device_ID.addItem("")
        self.comboBox_device_ID.addItem("")
        self.comboBox_device_ID.addItem("")
        self.comboBox_device_ID.addItem("")
        self.comboBox_device_ID.addItem("")
        self.comboBox_device_ID.addItem("")
        self.comboBox_device_ID.addItem("")
        self.horizontalLayout_8.addWidget(self.comboBox_device_ID)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_Antdelay = QtWidgets.QLabel(self.layoutWidget)
        self.label_Antdelay.setObjectName("label_Antdelay")
        self.horizontalLayout_2.addWidget(self.label_Antdelay)
        self.Spin_Box_Antdelay = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.Spin_Box_Antdelay.setDecimals(0)
        self.Spin_Box_Antdelay.setMinimum(0.0)
        self.Spin_Box_Antdelay.setMaximum(65535.0)
        self.Spin_Box_Antdelay.setProperty("value", 32965.0)
        self.Spin_Box_Antdelay.setObjectName("Spin_Box_Antdelay")
        self.horizontalLayout_2.addWidget(self.Spin_Box_Antdelay)
        self.label_reference_dis = QtWidgets.QLabel(self.layoutWidget)
        self.label_reference_dis.setObjectName("label_reference_dis")
        self.horizontalLayout_2.addWidget(self.label_reference_dis)
        self.Spin_Box_reference_dis = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.Spin_Box_reference_dis.setDecimals(0)
        self.Spin_Box_reference_dis.setMinimum(0.0)
        self.Spin_Box_reference_dis.setMaximum(65535.0)
        self.Spin_Box_reference_dis.setProperty("value", 814.0)
        self.Spin_Box_reference_dis.setObjectName("Spin_Box_reference_dis")
        self.horizontalLayout_2.addWidget(self.Spin_Box_reference_dis)
        self.btn_auto_calibration = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_auto_calibration.setObjectName("btn_auto_calibration")
        self.horizontalLayout_2.addWidget(self.btn_auto_calibration)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_air_baudrate = QtWidgets.QLabel(self.layoutWidget)
        self.label_air_baudrate.setObjectName("label_air_baudrate")
        self.horizontalLayout_9.addWidget(self.label_air_baudrate)
        self.comboBox_air_baudrate = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_air_baudrate.setObjectName("comboBox_air_baudrate")
        self.comboBox_air_baudrate.addItem("")
        self.comboBox_air_baudrate.addItem("")
        self.comboBox_air_baudrate.addItem("")
        self.horizontalLayout_9.addWidget(self.comboBox_air_baudrate)
        self.label_serial_baudrate = QtWidgets.QLabel(self.layoutWidget)
        self.label_serial_baudrate.setObjectName("label_serial_baudrate")
        self.horizontalLayout_9.addWidget(self.label_serial_baudrate)
        self.comboBox_serial_baudrate = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_serial_baudrate.setObjectName("comboBox_serial_baudrate")
        self.comboBox_serial_baudrate.addItem("")
        self.comboBox_serial_baudrate.addItem("")
        self.comboBox_serial_baudrate.addItem("")
        self.comboBox_serial_baudrate.addItem("")
        self.comboBox_serial_baudrate.addItem("")
        self.comboBox_serial_baudrate.addItem("")
        self.comboBox_serial_baudrate.addItem("")
        self.comboBox_serial_baudrate.addItem("")
        self.comboBox_serial_baudrate.addItem("")
        self.comboBox_serial_baudrate.addItem("")
        self.horizontalLayout_9.addWidget(self.comboBox_serial_baudrate)
        self.label_Device_Mode = QtWidgets.QLabel(self.layoutWidget)
        self.label_Device_Mode.setObjectName("label_Device_Mode")
        self.horizontalLayout_9.addWidget(self.label_Device_Mode)
        self.comboBox_Device_Mode = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_Device_Mode.setObjectName("comboBox_Device_Mode")
        self.comboBox_Device_Mode.addItem("")
        self.comboBox_Device_Mode.addItem("")
        self.horizontalLayout_9.addWidget(self.comboBox_Device_Mode)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_10.addWidget(self.label_3)
        self.spinBox_localAP_x = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_localAP_x.setMinimum(-32767)
        self.spinBox_localAP_x.setMaximum(32767)
        self.spinBox_localAP_x.setObjectName("spinBox_localAP_x")
        self.horizontalLayout_10.addWidget(self.spinBox_localAP_x)
        self.spinBox_localAP_y = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_localAP_y.setMinimum(-32767)
        self.spinBox_localAP_y.setMaximum(32767)
        self.spinBox_localAP_y.setObjectName("spinBox_localAP_y")
        self.horizontalLayout_10.addWidget(self.spinBox_localAP_y)
        self.spinBox_localAP_z = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_localAP_z.setMinimum(-32767)
        self.spinBox_localAP_z.setMaximum(32767)
        self.spinBox_localAP_z.setObjectName("spinBox_localAP_z")
        self.horizontalLayout_10.addWidget(self.spinBox_localAP_z)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.btn_write_para = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_write_para.setObjectName("btn_write_para")
        self.horizontalLayout_11.addWidget(self.btn_write_para)
        self.btn_read_para = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_read_para.setObjectName("btn_read_para")
        self.horizontalLayout_11.addWidget(self.btn_read_para)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.s2__clear_button = QtWidgets.QPushButton(self.tab_4)
        self.s2__clear_button.setGeometry(QtCore.QRect(440, 260, 61, 31))
        self.s2__clear_button.setObjectName("s2__clear_button")
        self.hex_receive = QtWidgets.QCheckBox(self.tab_4)
        self.hex_receive.setGeometry(QtCore.QRect(440, 220, 71, 16))
        self.hex_receive.setObjectName("hex_receive")
        self.hex_send = QtWidgets.QCheckBox(self.tab_4)
        self.hex_send.setGeometry(QtCore.QRect(440, 370, 71, 16))
        self.hex_send.setObjectName("hex_send")
        self.verticalGroupBox_2 = QtWidgets.QGroupBox(self.tab_4)
        self.verticalGroupBox_2.setGeometry(QtCore.QRect(40, 360, 371, 121))
        self.verticalGroupBox_2.setObjectName("verticalGroupBox_2")
        self.s3__send_text = QtWidgets.QTextEdit(self.verticalGroupBox_2)
        self.s3__send_text.setGeometry(QtCore.QRect(10, 20, 351, 61))
        self.s3__send_text.setObjectName("s3__send_text")
        self.layoutWidget_2 = QtWidgets.QWidget(self.verticalGroupBox_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(30, 90, 248, 22))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout.addWidget(self.lineEdit_3)
        self.timer_send_cb = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.timer_send_cb.setObjectName("timer_send_cb")
        self.horizontalLayout.addWidget(self.timer_send_cb)
        self.dw = QtWidgets.QLabel(self.layoutWidget_2)
        self.dw.setObjectName("dw")
        self.horizontalLayout.addWidget(self.dw)
        self.verticalGroupBox = QtWidgets.QGroupBox(self.tab_4)
        self.verticalGroupBox.setGeometry(QtCore.QRect(40, 210, 371, 141))
        self.verticalGroupBox.setObjectName("verticalGroupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalGroupBox)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.s2__receive_text = QtWidgets.QTextBrowser(self.verticalGroupBox)
        self.s2__receive_text.setObjectName("s2__receive_text")
        self.verticalLayout.addWidget(self.s2__receive_text)
        self.s3__clear_button = QtWidgets.QPushButton(self.tab_4)
        self.s3__clear_button.setGeometry(QtCore.QRect(440, 440, 61, 31))
        self.s3__clear_button.setObjectName("s3__clear_button")
        self.s3__send_button = QtWidgets.QPushButton(self.tab_4)
        self.s3__send_button.setGeometry(QtCore.QRect(440, 400, 61, 31))
        self.s3__send_button.setObjectName("s3__send_button")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(370, 10, 106, 170))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_Tatrget_x = QtWidgets.QLabel(self.groupBox)
        self.label_Tatrget_x.setObjectName("label_Tatrget_x")
        self.horizontalLayout_3.addWidget(self.label_Tatrget_x)
        self.Spin_Box_Tatrget_x = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.Spin_Box_Tatrget_x.setReadOnly(True)
        self.Spin_Box_Tatrget_x.setDecimals(0)
        self.Spin_Box_Tatrget_x.setMinimum(-100000.0)
        self.Spin_Box_Tatrget_x.setMaximum(100000.0)
        self.Spin_Box_Tatrget_x.setObjectName("Spin_Box_Tatrget_x")
        self.horizontalLayout_3.addWidget(self.Spin_Box_Tatrget_x)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_Tatrget_y = QtWidgets.QLabel(self.groupBox)
        self.label_Tatrget_y.setObjectName("label_Tatrget_y")
        self.horizontalLayout_4.addWidget(self.label_Tatrget_y)
        self.Spin_Box_Tatrget_y = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.Spin_Box_Tatrget_y.setReadOnly(True)
        self.Spin_Box_Tatrget_y.setDecimals(0)
        self.Spin_Box_Tatrget_y.setMinimum(-100000.0)
        self.Spin_Box_Tatrget_y.setMaximum(100000.0)
        self.Spin_Box_Tatrget_y.setObjectName("Spin_Box_Tatrget_y")
        self.horizontalLayout_4.addWidget(self.Spin_Box_Tatrget_y)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_Tatrget_z = QtWidgets.QLabel(self.groupBox)
        self.label_Tatrget_z.setObjectName("label_Tatrget_z")
        self.horizontalLayout_5.addWidget(self.label_Tatrget_z)
        self.Spin_Box_Tatrget_z = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.Spin_Box_Tatrget_z.setReadOnly(True)
        self.Spin_Box_Tatrget_z.setDecimals(0)
        self.Spin_Box_Tatrget_z.setMinimum(-100000.0)
        self.Spin_Box_Tatrget_z.setMaximum(100000.0)
        self.Spin_Box_Tatrget_z.setObjectName("Spin_Box_Tatrget_z")
        self.horizontalLayout_5.addWidget(self.Spin_Box_Tatrget_z)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.Trace_Start = QtWidgets.QPushButton(self.groupBox)
        self.Trace_Start.setObjectName("Trace_Start")
        self.verticalLayout_2.addWidget(self.Trace_Start)
        self.Trace_Stop = QtWidgets.QPushButton(self.groupBox)
        self.Trace_Stop.setObjectName("Trace_Stop")
        self.verticalLayout_2.addWidget(self.Trace_Stop)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_4.setGeometry(QtCore.QRect(480, 10, 134, 262))
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_Dis1 = QtWidgets.QLabel(self.groupBox_4)
        self.label_Dis1.setObjectName("label_Dis1")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_Dis1)
        self.Spin_Box_Dis1 = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.Spin_Box_Dis1.setDecimals(2)
        self.Spin_Box_Dis1.setMinimum(-1000.0)
        self.Spin_Box_Dis1.setMaximum(100000.0)
        self.Spin_Box_Dis1.setObjectName("Spin_Box_Dis1")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.Spin_Box_Dis1)
        self.label_Dis2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_Dis2.setObjectName("label_Dis2")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_Dis2)
        self.Spin_Box_Dis2 = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.Spin_Box_Dis2.setDecimals(2)
        self.Spin_Box_Dis2.setMinimum(-1000.0)
        self.Spin_Box_Dis2.setMaximum(100000.0)
        self.Spin_Box_Dis2.setObjectName("Spin_Box_Dis2")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.Spin_Box_Dis2)
        self.label_Dis3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_Dis3.setObjectName("label_Dis3")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_Dis3)
        self.Spin_Box_Dis3 = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.Spin_Box_Dis3.setDecimals(2)
        self.Spin_Box_Dis3.setMinimum(-1000.0)
        self.Spin_Box_Dis3.setMaximum(100000.0)
        self.Spin_Box_Dis3.setObjectName("Spin_Box_Dis3")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.Spin_Box_Dis3)
        self.label_Dis4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_Dis4.setObjectName("label_Dis4")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_Dis4)
        self.Spin_Box_Dis4 = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.Spin_Box_Dis4.setDecimals(2)
        self.Spin_Box_Dis4.setMinimum(-1000.0)
        self.Spin_Box_Dis4.setMaximum(100000.0)
        self.Spin_Box_Dis4.setObjectName("Spin_Box_Dis4")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.Spin_Box_Dis4)
        self.label_Dis5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_Dis5.setObjectName("label_Dis5")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_Dis5)
        self.Spin_Box_Dis5 = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.Spin_Box_Dis5.setDecimals(2)
        self.Spin_Box_Dis5.setMinimum(-1000.0)
        self.Spin_Box_Dis5.setMaximum(100000.0)
        self.Spin_Box_Dis5.setObjectName("Spin_Box_Dis5")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.Spin_Box_Dis5)
        self.label_Dis6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_Dis6.setObjectName("label_Dis6")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_Dis6)
        self.Spin_Box_Dis6 = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.Spin_Box_Dis6.setDecimals(2)
        self.Spin_Box_Dis6.setMinimum(-1000.0)
        self.Spin_Box_Dis6.setMaximum(100000.0)
        self.Spin_Box_Dis6.setObjectName("Spin_Box_Dis6")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.Spin_Box_Dis6)
        self.Spin_Box_Dis7 = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.Spin_Box_Dis7.setDecimals(2)
        self.Spin_Box_Dis7.setMinimum(-1000.0)
        self.Spin_Box_Dis7.setMaximum(100000.0)
        self.Spin_Box_Dis7.setObjectName("Spin_Box_Dis7")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.Spin_Box_Dis7)
        self.label_Dis7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_Dis7.setObjectName("label_Dis7")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_Dis7)
        self.label_Dis8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_Dis8.setObjectName("label_Dis8")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_Dis8)
        self.Spin_Box_Dis8 = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.Spin_Box_Dis8.setDecimals(2)
        self.Spin_Box_Dis8.setMinimum(-1000.0)
        self.Spin_Box_Dis8.setMaximum(100000.0)
        self.Spin_Box_Dis8.setObjectName("Spin_Box_Dis8")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.Spin_Box_Dis8)
        self.label_Dis6_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_Dis6_2.setObjectName("label_Dis6_2")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_Dis6_2)
        self.Spin_Box_Dis9 = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.Spin_Box_Dis9.setDecimals(2)
        self.Spin_Box_Dis9.setMinimum(-1000.0)
        self.Spin_Box_Dis9.setMaximum(100000.0)
        self.Spin_Box_Dis9.setObjectName("Spin_Box_Dis9")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.Spin_Box_Dis9)
        self.verticalLayout_6.addLayout(self.formLayout_3)
        self.groupBox_AP_Position = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_AP_Position.setGeometry(QtCore.QRect(10, 10, 344, 260))
        self.groupBox_AP_Position.setObjectName("groupBox_AP_Position")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_AP_Position)
        self.gridLayout.setObjectName("gridLayout")
        self.label_x1 = QtWidgets.QLabel(self.groupBox_AP_Position)
        self.label_x1.setLineWidth(6)
        self.label_x1.setObjectName("label_x1")
        self.gridLayout.addWidget(self.label_x1, 0, 0, 1, 1)
        self.Spin_Box_x1 = QtWidgets.QDoubleSpinBox(self.groupBox_AP_Position)
        self.Spin_Box_x1.setDecimals(0)
        self.Spin_Box_x1.setMinimum(-1000.0)
        self.Spin_Box_x1.setMaximum(1000.0)
        self.Spin_Box_x1.setProperty("value", -60.0)
        self.Spin_Box_x1.setObjectName("Spin_Box_x1")
        self.gridLayout.addWidget(self.Spin_Box_x1, 0, 1, 1, 1)
        self.label_y1 = QtWidgets.QLabel(self.groupBox_AP_Position)
        self.label_y1.setLineWidth(6)
        self.label_y1.setObjectName("label_y1")
        self.gridLayout.addWidget(self.label_y1, 0, 2, 1, 1)
        self.Spin_Box_y1 = QtWidgets.QDoubleSpinBox(self.groupBox_AP_Position)
        self.Spin_Box_y1.setDecimals(0)
        self.Spin_Box_y1.setMinimum(-1000.0)
        self.Spin_Box_y1.setMaximum(1000.0)
        self.Spin_Box_y1.setProperty("value", 60.0)
        self.Spin_Box_y1.setObjectName("Spin_Box_y1")
        self.gridLayout.addWidget(self.Spin_Box_y1, 0, 3, 1, 1)
        self.label_z1 = QtWidgets.QLabel(self.groupBox_AP_Position)
        self.label_z1.setLineWidth(6)
        self.label_z1.setObjectName("label_z1")
        self.gridLayout.addWidget(self.label_z1, 0, 4, 1, 1)
        self.Spin_Box_z1 = QtWidgets.QDoubleSpinBox(self.groupBox_AP_Position)
        self.Spin_Box_z1.setDecimals(0)
        self.Spin_Box_z1.setMinimum(-1000.0)
        self.Spin_Box_z1.setMaximum(1000.0)
        self.Spin_Box_z1.setObjectName("Spin_Box_z1")
        self.gridLayout.addWidget(self.Spin_Box_z1, 0, 5, 1, 1)
        self.label_x2 = QtWidgets.QLabel(self.groupBox_AP_Position)
        self.label_x2.setObjectName("label_x2")
        self.gridLayout.addWidget(self.label_x2, 1, 0, 1, 1)
        self.Spin_Box_x2 = QtWidgets.QDoubleSpinBox(self.groupBox_AP_Position)
        self.Spin_Box_x2.setDecimals(0)
        self.Spin_Box_x2.setMinimum(-1000.0)
        self.Spin_Box_x2.setMaximum(1000.0)
        self.Spin_Box_x2.setSingleStep(0.0)
        self.Spin_Box_x2.setProperty("value", 0.0)
        self.Spin_Box_x2.setObjectName("Spin_Box_x2")
        self.gridLayout.addWidget(self.Spin_Box_x2, 1, 1, 1, 1)
        self.label_y2 = QtWidgets.QLabel(self.groupBox_AP_Position)
        self.label_y2.setObjectName("label_y2")
        self.gridLayout.addWidget(self.label_y2, 1, 2, 1, 1)
        self.Spin_Box_y2 = QtWidgets.QDoubleSpinBox(self.groupBox_AP_Position)
        self.Spin_Box_y2.setDecimals(0)
        self.Spin_Box_y2.setMinimum(-1000.0)
        self.Spin_Box_y2.setMaximum(1000.0)
        self.Spin_Box_y2.setProperty("value", 60.0)
        self.Spin_Box_y2.setObjectName("Spin_Box_y2")
        self.gridLayout.addWidget(self.Spin_Box_y2, 1, 3, 1, 1)
        self.label_z2 = QtWidgets.QLabel(self.groupBox_AP_Position)
        self.label_z2.setObjectName("label_z2")
        self.gridLayout.addWidget(self.label_z2, 1, 4, 1, 1)
        self.Spin_Box_z2 = QtWidgets.QDoubleSpinBox(self.groupBox_AP_Position)
        self.Spin_Box_z2.setDecimals(0)
        self.Spin_Box_z2.setMinimum(-1000.0)
        self.Spin_Box_z2.setMaximum(1000.0)
        self.Spin_Box_z2.setObjectName("Spin_Box_z2")
        self.gridLayout.addWidget(self.Spin_Box_z2, 1, 5, 1, 1)
        self.label_x3 = QtWidgets.QLabel(self.groupBox_AP_Position)
        self.label_x3.setObjectName("label_x3")
        self.gridLayout.addWidget(self.label_x3, 2, 0, 1, 1)
        self.Spin_Box_x3 = QtWidgets.QDoubleSpinBox(self.groupBox_AP_Position)
        self.Spin_Box_x3.setDecimals(0)
        self.Spin_Box_x3.setMinimum(-1000.0)
        self.Spin_Box_x3.setMaximum(1000.0)
        self.Spin_Box_x3.setProperty("value", 60.0)
        self.Spin_Box_x3.setObjectName("Spin_Box_x3")
        self.gridLayout.addWidget(self.Spin_Box_x3, 2, 1, 1, 1)
        self.label_y3 = QtWidgets.QLabel(self.groupBox_AP_Position)
        self.label_y3.setObjectName("label_y3")
        self.gridLayout.addWidget(self.label_y3, 2, 2, 1, 1)
        self.Spin_Box_y3 = QtWidgets.QDoubleSpinBox(self.groupBox_AP_Position)
        self.Spin_Box_y3.setDecimals(0)
        self.Spin_Box_y3.setMinimum(-1000.0)
        self.Spin_Box_y3.setMaximum(1000.0)
        self.Spin_Box_y3.setProperty("value", 60.0)
        self.Spin_Box_y3.setObjectName("Spin_Box_y3")
        self.gridLayout.addWidget(self.Spin_Box_y3, 2, 3, 1, 1)
        self.label_z3 = QtWidgets.QLabel(self.groupBox_AP_Position)
        self.label_z3.setObjectName("label_z3")
        self.gridLayout.addWidget(self.label_z3, 2, 4, 1, 1)
        self.Spin_Box_z3 = QtWidgets.QDoubleSpinBox(self.groupBox_AP_Position)
        self.Spin_Box_z3.setDecimals(0)
        self.Spin_Box_z3.setMinimum(-1000.0)
        self.Spin_Box_z3.setMaximum(1000.0)
        self.Spin_Box_z3.setObjectName("Spin_Box_z3")
        self.gridLayout.addWidget(self.Spin_Box_z3, 2, 5, 1, 1)
        self.label_x4 = QtWidgets.QLabel(self.groupBox_AP_Position)
        self.label_x4.setObjectName("label_x4")
        self.gridLayout.addWidget(self.label_x4, 3, 0, 1, 1)
        self.Spin_Box_x4 = QtWidgets.QDoubleSpinBox(self.groupBox_AP_Position)
        self.Spin_Box_x4.setDecimals(0)
        self.Spin_Box_x4.setMinimum(-1000.0)
        self.Spin_Box_x4.setMaximum(1000.0)
        self.Spin_Box_x4.setProperty("value", -60.0)
        self.Spin_Box_x4.setObjectName("Spin_Box_x4")
        self.gridLayout.addWidget(self.Spin_Box_x4, 3, 1, 1, 1)
        self.label_y4 = QtWidgets.QLabel(self.groupBox_AP_Position)
        self.label_y4.setObjectName("label_y4")
        self.gridLayout.addWidget(self.label_y4, 3, 2, 1, 1)
        self.Spin_Box_y4 = QtWidgets.QDoubleSpinBox(self.groupBox_AP_Position)
        self.Spin_Box_y4.setDecimals(0)
        self.Spin_Box_y4.setMinimum(-1000.0)
        self.Spin_Box_y4.setMaximum(1000.0)
        self.Spin_Box_y4.setObjectName("Spin_Box_y4")
        self.gridLayout.addWidget(self.Spin_Box_y4, 3, 3, 1, 1)
        self.label_z4 = QtWidgets.QLabel(self.groupBox_AP_Position)
        self.label_z4.setObjectName("label_z4")
        self.gridLayout.addWidget(self.label_z4, 3, 4, 1, 1)
        self.Spin_Box_z4 = QtWidgets.QDoubleSpinBox(self.groupBox_AP_Position)
        self.Spin_Box_z4.setDecimals(0)
        self.Spin_Box_z4.setMinimum(-1000.0)
        self.Spin_Box_z4.setMaximum(1000.0)
        self.Spin_Box_z4.setObjectName("Spin_Box_z4")
        self.gridLayout.addWidget(self.Spin_Box_z4, 3, 5, 1, 1)
        self.label_x5 = QtWidgets.QLabel(self.groupBox_AP_Position)
        self.label_x5.setObjectName("label_x5")
        self.gridLayout.addWidget(self.label_x5, 4, 0, 1, 1)
        self.Spin_Box_x5 = QtWidgets.QDoubleSpinBox(self.groupBox_AP_Position)
        self.Spin_Box_x5.setDecimals(0)
        self.Spin_Box_x5.setMinimum(-1000.0)
        self.Spin_Box_x5.setMaximum(1000.0)
        self.Spin_Box_x5.setProperty("value", -60.0)
        self.Spin_Box_x5.setObjectName("Spin_Box_x5")
        self.gridLayout.addWidget(self.Spin_Box_x5, 4, 1, 1, 1)
        self.label_y5 = QtWidgets.QLabel(self.groupBox_AP_Position)
        self.label_y5.setObjectName("label_y5")
        self.gridLayout.addWidget(self.label_y5, 4, 2, 1, 1)
        self.Spin_Box_y5 = QtWidgets.QDoubleSpinBox(self.groupBox_AP_Position)
        self.Spin_Box_y5.setDecimals(0)
        self.Spin_Box_y5.setMinimum(-1000.0)
        self.Spin_Box_y5.setMaximum(1000.0)
        self.Spin_Box_y5.setProperty("value", -60.0)
        self.Spin_Box_y5.setObjectName("Spin_Box_y5")
        self.gridLayout.addWidget(self.Spin_Box_y5, 4, 3, 1, 1)
        self.label_z5 = QtWidgets.QLabel(self.groupBox_AP_Position)
        self.label_z5.setObjectName("label_z5")
        self.gridLayout.addWidget(self.label_z5, 4, 4, 1, 1)
        self.Spin_Box_z5 = QtWidgets.QDoubleSpinBox(self.groupBox_AP_Position)
        self.Spin_Box_z5.setDecimals(0)
        self.Spin_Box_z5.setMinimum(-1000.0)
        self.Spin_Box_z5.setMaximum(1000.0)
        self.Spin_Box_z5.setObjectName("Spin_Box_z5")
        self.gridLayout.addWidget(self.Spin_Box_z5, 4, 5, 1, 1)
        self.label_x6 = QtWidgets.QLabel(self.groupBox_AP_Position)
        self.label_x6.setObjectName("label_x6")
        self.gridLayout.addWidget(self.label_x6, 5, 0, 1, 1)
        self.Spin_Box_x6 = QtWidgets.QDoubleSpinBox(self.groupBox_AP_Position)
        self.Spin_Box_x6.setDecimals(0)
        self.Spin_Box_x6.setMinimum(-1000.0)
        self.Spin_Box_x6.setMaximum(1000.0)
        self.Spin_Box_x6.setProperty("value", 60.0)
        self.Spin_Box_x6.setObjectName("Spin_Box_x6")
        self.gridLayout.addWidget(self.Spin_Box_x6, 5, 1, 1, 1)
        self.label_y6 = QtWidgets.QLabel(self.groupBox_AP_Position)
        self.label_y6.setObjectName("label_y6")
        self.gridLayout.addWidget(self.label_y6, 5, 2, 1, 1)
        self.Spin_Box_y6 = QtWidgets.QDoubleSpinBox(self.groupBox_AP_Position)
        self.Spin_Box_y6.setDecimals(0)
        self.Spin_Box_y6.setMinimum(-1000.0)
        self.Spin_Box_y6.setMaximum(1000.0)
        self.Spin_Box_y6.setProperty("value", -60.0)
        self.Spin_Box_y6.setObjectName("Spin_Box_y6")
        self.gridLayout.addWidget(self.Spin_Box_y6, 5, 3, 1, 1)
        self.label_z6 = QtWidgets.QLabel(self.groupBox_AP_Position)
        self.label_z6.setObjectName("label_z6")
        self.gridLayout.addWidget(self.label_z6, 5, 4, 1, 1)
        self.Spin_Box_z6 = QtWidgets.QDoubleSpinBox(self.groupBox_AP_Position)
        self.Spin_Box_z6.setDecimals(0)
        self.Spin_Box_z6.setMinimum(-1000.0)
        self.Spin_Box_z6.setMaximum(1000.0)
        self.Spin_Box_z6.setObjectName("Spin_Box_z6")
        self.gridLayout.addWidget(self.Spin_Box_z6, 5, 5, 1, 1)
        self.label_x7 = QtWidgets.QLabel(self.groupBox_AP_Position)
        self.label_x7.setObjectName("label_x7")
        self.gridLayout.addWidget(self.label_x7, 6, 0, 1, 1)
        self.Spin_Box_x7 = QtWidgets.QDoubleSpinBox(self.groupBox_AP_Position)
        self.Spin_Box_x7.setDecimals(0)
        self.Spin_Box_x7.setMinimum(-1000.0)
        self.Spin_Box_x7.setMaximum(1000.0)
        self.Spin_Box_x7.setProperty("value", 0.0)
        self.Spin_Box_x7.setObjectName("Spin_Box_x7")
        self.gridLayout.addWidget(self.Spin_Box_x7, 6, 1, 1, 1)
        self.label_y7 = QtWidgets.QLabel(self.groupBox_AP_Position)
        self.label_y7.setObjectName("label_y7")
        self.gridLayout.addWidget(self.label_y7, 6, 2, 1, 1)
        self.Spin_Box_y7 = QtWidgets.QDoubleSpinBox(self.groupBox_AP_Position)
        self.Spin_Box_y7.setDecimals(0)
        self.Spin_Box_y7.setMinimum(-1000.0)
        self.Spin_Box_y7.setMaximum(1000.0)
        self.Spin_Box_y7.setObjectName("Spin_Box_y7")
        self.gridLayout.addWidget(self.Spin_Box_y7, 6, 3, 1, 1)
        self.label_z7 = QtWidgets.QLabel(self.groupBox_AP_Position)
        self.label_z7.setObjectName("label_z7")
        self.gridLayout.addWidget(self.label_z7, 6, 4, 1, 1)
        self.Spin_Box_z7 = QtWidgets.QDoubleSpinBox(self.groupBox_AP_Position)
        self.Spin_Box_z7.setDecimals(0)
        self.Spin_Box_z7.setMinimum(-1000.0)
        self.Spin_Box_z7.setMaximum(1000.0)
        self.Spin_Box_z7.setObjectName("Spin_Box_z7")
        self.gridLayout.addWidget(self.Spin_Box_z7, 6, 5, 1, 1)
        self.label_x8 = QtWidgets.QLabel(self.groupBox_AP_Position)
        self.label_x8.setObjectName("label_x8")
        self.gridLayout.addWidget(self.label_x8, 7, 0, 1, 1)
        self.Spin_Box_x8 = QtWidgets.QDoubleSpinBox(self.groupBox_AP_Position)
        self.Spin_Box_x8.setDecimals(0)
        self.Spin_Box_x8.setMinimum(-1000.0)
        self.Spin_Box_x8.setMaximum(1000.0)
        self.Spin_Box_x8.setProperty("value", 0.0)
        self.Spin_Box_x8.setObjectName("Spin_Box_x8")
        self.gridLayout.addWidget(self.Spin_Box_x8, 7, 1, 1, 1)
        self.label_y8 = QtWidgets.QLabel(self.groupBox_AP_Position)
        self.label_y8.setObjectName("label_y8")
        self.gridLayout.addWidget(self.label_y8, 7, 2, 1, 1)
        self.Spin_Box_y8 = QtWidgets.QDoubleSpinBox(self.groupBox_AP_Position)
        self.Spin_Box_y8.setDecimals(0)
        self.Spin_Box_y8.setMinimum(-1000.0)
        self.Spin_Box_y8.setMaximum(1000.0)
        self.Spin_Box_y8.setObjectName("Spin_Box_y8")
        self.gridLayout.addWidget(self.Spin_Box_y8, 7, 3, 1, 1)
        self.label_z8 = QtWidgets.QLabel(self.groupBox_AP_Position)
        self.label_z8.setObjectName("label_z8")
        self.gridLayout.addWidget(self.label_z8, 7, 4, 1, 1)
        self.Spin_Box_z8 = QtWidgets.QDoubleSpinBox(self.groupBox_AP_Position)
        self.Spin_Box_z8.setDecimals(0)
        self.Spin_Box_z8.setMinimum(-1000.0)
        self.Spin_Box_z8.setMaximum(1000.0)
        self.Spin_Box_z8.setObjectName("Spin_Box_z8")
        self.gridLayout.addWidget(self.Spin_Box_z8, 7, 5, 1, 1)
        self.label_x9 = QtWidgets.QLabel(self.groupBox_AP_Position)
        self.label_x9.setObjectName("label_x9")
        self.gridLayout.addWidget(self.label_x9, 8, 0, 1, 1)
        self.Spin_Box_x9 = QtWidgets.QDoubleSpinBox(self.groupBox_AP_Position)
        self.Spin_Box_x9.setDecimals(0)
        self.Spin_Box_x9.setMinimum(-1000.0)
        self.Spin_Box_x9.setMaximum(1000.0)
        self.Spin_Box_x9.setProperty("value", 0.0)
        self.Spin_Box_x9.setObjectName("Spin_Box_x9")
        self.gridLayout.addWidget(self.Spin_Box_x9, 8, 1, 1, 1)
        self.label_y9 = QtWidgets.QLabel(self.groupBox_AP_Position)
        self.label_y9.setObjectName("label_y9")
        self.gridLayout.addWidget(self.label_y9, 8, 2, 1, 1)
        self.Spin_Box_y9 = QtWidgets.QDoubleSpinBox(self.groupBox_AP_Position)
        self.Spin_Box_y9.setDecimals(0)
        self.Spin_Box_y9.setMinimum(-1000.0)
        self.Spin_Box_y9.setMaximum(1000.0)
        self.Spin_Box_y9.setObjectName("Spin_Box_y9")
        self.gridLayout.addWidget(self.Spin_Box_y9, 8, 3, 1, 1)
        self.label_z9 = QtWidgets.QLabel(self.groupBox_AP_Position)
        self.label_z9.setObjectName("label_z9")
        self.gridLayout.addWidget(self.label_z9, 8, 4, 1, 1)
        self.Spin_Box_z9 = QtWidgets.QDoubleSpinBox(self.groupBox_AP_Position)
        self.Spin_Box_z9.setDecimals(0)
        self.Spin_Box_z9.setMinimum(-1000.0)
        self.Spin_Box_z9.setMaximum(1000.0)
        self.Spin_Box_z9.setObjectName("Spin_Box_z9")
        self.gridLayout.addWidget(self.Spin_Box_z9, 8, 5, 1, 1)
        self.tableWidget_monitor = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_monitor.setGeometry(QtCore.QRect(10, 280, 541, 241))
        self.tableWidget_monitor.setMinimumSize(QtCore.QSize(441, 181))
        self.tableWidget_monitor.setLineWidth(1)
        self.tableWidget_monitor.setGridStyle(QtCore.Qt.CustomDashLine)
        self.tableWidget_monitor.setObjectName("tableWidget_monitor")
        self.tableWidget_monitor.setColumnCount(5)
        self.tableWidget_monitor.setRowCount(9)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_monitor.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_monitor.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_monitor.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_monitor.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_monitor.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_monitor.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_monitor.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_monitor.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_monitor.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_monitor.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_monitor.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_monitor.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_monitor.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_monitor.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_monitor.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_monitor.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_monitor.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_monitor.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_monitor.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_monitor.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_monitor.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_monitor.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_monitor.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_monitor.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_monitor.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_monitor.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_monitor.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_monitor.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_monitor.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_monitor.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_monitor.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_monitor.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_monitor.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_monitor.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_monitor.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_monitor.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_monitor.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_monitor.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_monitor.setItem(4, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_monitor.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_monitor.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_monitor.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_monitor.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_monitor.setItem(5, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_monitor.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_monitor.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_monitor.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_monitor.setItem(6, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_monitor.setItem(6, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_monitor.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_monitor.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_monitor.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_monitor.setItem(7, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_monitor.setItem(7, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_monitor.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_monitor.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_monitor.setItem(8, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_monitor.setItem(8, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_monitor.setItem(8, 4, item)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_6.setGeometry(QtCore.QRect(30, 70, 511, 351))
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Spin_Box_TEMPERATURE_4 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.Spin_Box_TEMPERATURE_4.setDecimals(2)
        self.Spin_Box_TEMPERATURE_4.setMinimum(-1000.0)
        self.Spin_Box_TEMPERATURE_4.setMaximum(100000.0)
        self.Spin_Box_TEMPERATURE_4.setObjectName("Spin_Box_TEMPERATURE_4")
        self.gridLayout_2.addWidget(self.Spin_Box_TEMPERATURE_4, 6, 3, 1, 1)
        self.Spin_Box_VOLTAGE_7 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.Spin_Box_VOLTAGE_7.setDecimals(2)
        self.Spin_Box_VOLTAGE_7.setMinimum(-1000.0)
        self.Spin_Box_VOLTAGE_7.setMaximum(100000.0)
        self.Spin_Box_VOLTAGE_7.setObjectName("Spin_Box_VOLTAGE_7")
        self.gridLayout_2.addWidget(self.Spin_Box_VOLTAGE_7, 9, 4, 1, 1)
        self.Spin_Box_VOLTAGE_2 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.Spin_Box_VOLTAGE_2.setDecimals(2)
        self.Spin_Box_VOLTAGE_2.setMinimum(-1000.0)
        self.Spin_Box_VOLTAGE_2.setMaximum(100000.0)
        self.Spin_Box_VOLTAGE_2.setObjectName("Spin_Box_VOLTAGE_2")
        self.gridLayout_2.addWidget(self.Spin_Box_VOLTAGE_2, 1, 4, 1, 1)
        self.Spin_Box_DLY_6 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.Spin_Box_DLY_6.setDecimals(0)
        self.Spin_Box_DLY_6.setMinimum(-1000.0)
        self.Spin_Box_DLY_6.setMaximum(100000.0)
        self.Spin_Box_DLY_6.setObjectName("Spin_Box_DLY_6")
        self.gridLayout_2.addWidget(self.Spin_Box_DLY_6, 8, 1, 1, 1)
        self.Spin_Box_DISTANCE_3 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.Spin_Box_DISTANCE_3.setDecimals(0)
        self.Spin_Box_DISTANCE_3.setMinimum(-1000.0)
        self.Spin_Box_DISTANCE_3.setMaximum(100000.0)
        self.Spin_Box_DISTANCE_3.setObjectName("Spin_Box_DISTANCE_3")
        self.gridLayout_2.addWidget(self.Spin_Box_DISTANCE_3, 4, 2, 1, 1)
        self.Spin_Box_DLY_5 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.Spin_Box_DLY_5.setDecimals(0)
        self.Spin_Box_DLY_5.setMinimum(-1000.0)
        self.Spin_Box_DLY_5.setMaximum(100000.0)
        self.Spin_Box_DLY_5.setObjectName("Spin_Box_DLY_5")
        self.gridLayout_2.addWidget(self.Spin_Box_DLY_5, 7, 1, 1, 1)
        self.Auto_Cal_Active_Box_6 = QtWidgets.QCheckBox(self.groupBox_6)
        self.Auto_Cal_Active_Box_6.setChecked(False)
        self.Auto_Cal_Active_Box_6.setObjectName("Auto_Cal_Active_Box_6")
        self.gridLayout_2.addWidget(self.Auto_Cal_Active_Box_6, 8, 5, 1, 1)
        self.label_Dis1_4 = QtWidgets.QLabel(self.groupBox_6)
        self.label_Dis1_4.setObjectName("label_Dis1_4")
        self.gridLayout_2.addWidget(self.label_Dis1_4, 0, 0, 1, 1)
        self.Spin_Box_VOLTAGE_6 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.Spin_Box_VOLTAGE_6.setDecimals(2)
        self.Spin_Box_VOLTAGE_6.setMinimum(-1000.0)
        self.Spin_Box_VOLTAGE_6.setMaximum(100000.0)
        self.Spin_Box_VOLTAGE_6.setObjectName("Spin_Box_VOLTAGE_6")
        self.gridLayout_2.addWidget(self.Spin_Box_VOLTAGE_6, 8, 4, 1, 1)
        self.label_Dis4_4 = QtWidgets.QLabel(self.groupBox_6)
        self.label_Dis4_4.setObjectName("label_Dis4_4")
        self.gridLayout_2.addWidget(self.label_Dis4_4, 6, 0, 1, 1)
        self.Spin_Box_VOLTAGE_8 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.Spin_Box_VOLTAGE_8.setDecimals(2)
        self.Spin_Box_VOLTAGE_8.setMinimum(-1000.0)
        self.Spin_Box_VOLTAGE_8.setMaximum(100000.0)
        self.Spin_Box_VOLTAGE_8.setObjectName("Spin_Box_VOLTAGE_8")
        self.gridLayout_2.addWidget(self.Spin_Box_VOLTAGE_8, 10, 4, 1, 1)
        self.label_Dis6_7 = QtWidgets.QLabel(self.groupBox_6)
        self.label_Dis6_7.setObjectName("label_Dis6_7")
        self.gridLayout_2.addWidget(self.label_Dis6_7, 8, 0, 1, 1)
        self.Spin_Box_DISTANCE_7 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.Spin_Box_DISTANCE_7.setDecimals(0)
        self.Spin_Box_DISTANCE_7.setMinimum(-1000.0)
        self.Spin_Box_DISTANCE_7.setMaximum(100000.0)
        self.Spin_Box_DISTANCE_7.setObjectName("Spin_Box_DISTANCE_7")
        self.gridLayout_2.addWidget(self.Spin_Box_DISTANCE_7, 9, 2, 1, 1)
        self.Spin_Box_DLY_1 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.Spin_Box_DLY_1.setDecimals(0)
        self.Spin_Box_DLY_1.setMinimum(-1000.0)
        self.Spin_Box_DLY_1.setMaximum(100000.0)
        self.Spin_Box_DLY_1.setObjectName("Spin_Box_DLY_1")
        self.gridLayout_2.addWidget(self.Spin_Box_DLY_1, 0, 1, 1, 1)
        self.Write_Flag__Box_2 = QtWidgets.QCheckBox(self.groupBox_6)
        self.Write_Flag__Box_2.setObjectName("Write_Flag__Box_2")
        self.gridLayout_2.addWidget(self.Write_Flag__Box_2, 1, 6, 1, 1)
        self.Write_Flag__Box_8 = QtWidgets.QCheckBox(self.groupBox_6)
        self.Write_Flag__Box_8.setObjectName("Write_Flag__Box_8")
        self.gridLayout_2.addWidget(self.Write_Flag__Box_8, 10, 6, 1, 1)
        self.label_Dis8_4 = QtWidgets.QLabel(self.groupBox_6)
        self.label_Dis8_4.setObjectName("label_Dis8_4")
        self.gridLayout_2.addWidget(self.label_Dis8_4, 10, 0, 1, 1)
        self.Spin_Box_DISTANCE_6 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.Spin_Box_DISTANCE_6.setDecimals(0)
        self.Spin_Box_DISTANCE_6.setMinimum(-1000.0)
        self.Spin_Box_DISTANCE_6.setMaximum(100000.0)
        self.Spin_Box_DISTANCE_6.setObjectName("Spin_Box_DISTANCE_6")
        self.gridLayout_2.addWidget(self.Spin_Box_DISTANCE_6, 8, 2, 1, 1)
        self.Spin_Box_DISTANCE_9 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.Spin_Box_DISTANCE_9.setDecimals(0)
        self.Spin_Box_DISTANCE_9.setMinimum(-1000.0)
        self.Spin_Box_DISTANCE_9.setMaximum(100000.0)
        self.Spin_Box_DISTANCE_9.setObjectName("Spin_Box_DISTANCE_9")
        self.gridLayout_2.addWidget(self.Spin_Box_DISTANCE_9, 13, 2, 1, 1)
        self.label_Dis5_4 = QtWidgets.QLabel(self.groupBox_6)
        self.label_Dis5_4.setObjectName("label_Dis5_4")
        self.gridLayout_2.addWidget(self.label_Dis5_4, 7, 0, 1, 1)
        self.Spin_Box_DLY_9 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.Spin_Box_DLY_9.setDecimals(0)
        self.Spin_Box_DLY_9.setMinimum(-1000.0)
        self.Spin_Box_DLY_9.setMaximum(100000.0)
        self.Spin_Box_DLY_9.setObjectName("Spin_Box_DLY_9")
        self.gridLayout_2.addWidget(self.Spin_Box_DLY_9, 13, 1, 1, 1)
        self.Spin_Box_TEMPERATURE_2 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.Spin_Box_TEMPERATURE_2.setDecimals(2)
        self.Spin_Box_TEMPERATURE_2.setMinimum(-1000.0)
        self.Spin_Box_TEMPERATURE_2.setMaximum(100000.0)
        self.Spin_Box_TEMPERATURE_2.setObjectName("Spin_Box_TEMPERATURE_2")
        self.gridLayout_2.addWidget(self.Spin_Box_TEMPERATURE_2, 1, 3, 1, 1)
        self.Auto_Cal_Active_Box_5 = QtWidgets.QCheckBox(self.groupBox_6)
        self.Auto_Cal_Active_Box_5.setChecked(False)
        self.Auto_Cal_Active_Box_5.setObjectName("Auto_Cal_Active_Box_5")
        self.gridLayout_2.addWidget(self.Auto_Cal_Active_Box_5, 7, 5, 1, 1)
        self.Spin_Box_DISTANCE_8 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.Spin_Box_DISTANCE_8.setDecimals(0)
        self.Spin_Box_DISTANCE_8.setMinimum(-1000.0)
        self.Spin_Box_DISTANCE_8.setMaximum(100000.0)
        self.Spin_Box_DISTANCE_8.setObjectName("Spin_Box_DISTANCE_8")
        self.gridLayout_2.addWidget(self.Spin_Box_DISTANCE_8, 10, 2, 1, 1)
        self.Auto_Cal_Active_Box_8 = QtWidgets.QCheckBox(self.groupBox_6)
        self.Auto_Cal_Active_Box_8.setChecked(False)
        self.Auto_Cal_Active_Box_8.setObjectName("Auto_Cal_Active_Box_8")
        self.gridLayout_2.addWidget(self.Auto_Cal_Active_Box_8, 10, 5, 1, 1)
        self.Spin_Box_VOLTAGE_4 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.Spin_Box_VOLTAGE_4.setDecimals(2)
        self.Spin_Box_VOLTAGE_4.setMinimum(-1000.0)
        self.Spin_Box_VOLTAGE_4.setMaximum(100000.0)
        self.Spin_Box_VOLTAGE_4.setObjectName("Spin_Box_VOLTAGE_4")
        self.gridLayout_2.addWidget(self.Spin_Box_VOLTAGE_4, 6, 4, 1, 1)
        self.Spin_Box_DISTANCE_2 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.Spin_Box_DISTANCE_2.setDecimals(0)
        self.Spin_Box_DISTANCE_2.setMinimum(-1000.0)
        self.Spin_Box_DISTANCE_2.setMaximum(100000.0)
        self.Spin_Box_DISTANCE_2.setObjectName("Spin_Box_DISTANCE_2")
        self.gridLayout_2.addWidget(self.Spin_Box_DISTANCE_2, 1, 2, 1, 1)
        self.Spin_Box_DLY_8 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.Spin_Box_DLY_8.setDecimals(0)
        self.Spin_Box_DLY_8.setMinimum(-1000.0)
        self.Spin_Box_DLY_8.setMaximum(100000.0)
        self.Spin_Box_DLY_8.setObjectName("Spin_Box_DLY_8")
        self.gridLayout_2.addWidget(self.Spin_Box_DLY_8, 10, 1, 1, 1)
        self.Spin_Box_VOLTAGE_1 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.Spin_Box_VOLTAGE_1.setDecimals(2)
        self.Spin_Box_VOLTAGE_1.setMinimum(-1000.0)
        self.Spin_Box_VOLTAGE_1.setMaximum(100000.0)
        self.Spin_Box_VOLTAGE_1.setObjectName("Spin_Box_VOLTAGE_1")
        self.gridLayout_2.addWidget(self.Spin_Box_VOLTAGE_1, 0, 4, 1, 1)
        self.Auto_Cal_Active_Box_7 = QtWidgets.QCheckBox(self.groupBox_6)
        self.Auto_Cal_Active_Box_7.setChecked(False)
        self.Auto_Cal_Active_Box_7.setObjectName("Auto_Cal_Active_Box_7")
        self.gridLayout_2.addWidget(self.Auto_Cal_Active_Box_7, 9, 5, 1, 1)
        self.Spin_Box_VOLTAGE_9 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.Spin_Box_VOLTAGE_9.setDecimals(2)
        self.Spin_Box_VOLTAGE_9.setMinimum(-1000.0)
        self.Spin_Box_VOLTAGE_9.setMaximum(100000.0)
        self.Spin_Box_VOLTAGE_9.setObjectName("Spin_Box_VOLTAGE_9")
        self.gridLayout_2.addWidget(self.Spin_Box_VOLTAGE_9, 13, 4, 1, 1)
        self.label_Dis2_4 = QtWidgets.QLabel(self.groupBox_6)
        self.label_Dis2_4.setObjectName("label_Dis2_4")
        self.gridLayout_2.addWidget(self.label_Dis2_4, 1, 0, 1, 1)
        self.Spin_Box_TEMPERATURE_8 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.Spin_Box_TEMPERATURE_8.setDecimals(2)
        self.Spin_Box_TEMPERATURE_8.setMinimum(-1000.0)
        self.Spin_Box_TEMPERATURE_8.setMaximum(100000.0)
        self.Spin_Box_TEMPERATURE_8.setObjectName("Spin_Box_TEMPERATURE_8")
        self.gridLayout_2.addWidget(self.Spin_Box_TEMPERATURE_8, 10, 3, 1, 1)
        self.Write_Flag__Box_5 = QtWidgets.QCheckBox(self.groupBox_6)
        self.Write_Flag__Box_5.setObjectName("Write_Flag__Box_5")
        self.gridLayout_2.addWidget(self.Write_Flag__Box_5, 7, 6, 1, 1)
        self.Spin_Box_DISTANCE_1 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.Spin_Box_DISTANCE_1.setDecimals(0)
        self.Spin_Box_DISTANCE_1.setMinimum(-1000.0)
        self.Spin_Box_DISTANCE_1.setMaximum(100000.0)
        self.Spin_Box_DISTANCE_1.setObjectName("Spin_Box_DISTANCE_1")
        self.gridLayout_2.addWidget(self.Spin_Box_DISTANCE_1, 0, 2, 1, 1)
        self.Spin_Box_TEMPERATURE_3 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.Spin_Box_TEMPERATURE_3.setDecimals(2)
        self.Spin_Box_TEMPERATURE_3.setMinimum(-1000.0)
        self.Spin_Box_TEMPERATURE_3.setMaximum(100000.0)
        self.Spin_Box_TEMPERATURE_3.setObjectName("Spin_Box_TEMPERATURE_3")
        self.gridLayout_2.addWidget(self.Spin_Box_TEMPERATURE_3, 4, 3, 1, 1)
        self.Auto_Cal_Active_Box_1 = QtWidgets.QCheckBox(self.groupBox_6)
        self.Auto_Cal_Active_Box_1.setChecked(False)
        self.Auto_Cal_Active_Box_1.setObjectName("Auto_Cal_Active_Box_1")
        self.gridLayout_2.addWidget(self.Auto_Cal_Active_Box_1, 0, 5, 1, 1)
        self.Spin_Box_VOLTAGE_5 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.Spin_Box_VOLTAGE_5.setDecimals(2)
        self.Spin_Box_VOLTAGE_5.setMinimum(-1000.0)
        self.Spin_Box_VOLTAGE_5.setMaximum(100000.0)
        self.Spin_Box_VOLTAGE_5.setObjectName("Spin_Box_VOLTAGE_5")
        self.gridLayout_2.addWidget(self.Spin_Box_VOLTAGE_5, 7, 4, 1, 1)
        self.Write_Flag__Box_6 = QtWidgets.QCheckBox(self.groupBox_6)
        self.Write_Flag__Box_6.setObjectName("Write_Flag__Box_6")
        self.gridLayout_2.addWidget(self.Write_Flag__Box_6, 8, 6, 1, 1)
        self.Spin_Box_DLY_2 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.Spin_Box_DLY_2.setDecimals(0)
        self.Spin_Box_DLY_2.setMinimum(-1000.0)
        self.Spin_Box_DLY_2.setMaximum(100000.0)
        self.Spin_Box_DLY_2.setObjectName("Spin_Box_DLY_2")
        self.gridLayout_2.addWidget(self.Spin_Box_DLY_2, 1, 1, 1, 1)
        self.Auto_Cal_Active_Box_4 = QtWidgets.QCheckBox(self.groupBox_6)
        self.Auto_Cal_Active_Box_4.setChecked(False)
        self.Auto_Cal_Active_Box_4.setObjectName("Auto_Cal_Active_Box_4")
        self.gridLayout_2.addWidget(self.Auto_Cal_Active_Box_4, 6, 5, 1, 1)
        self.Spin_Box_TEMPERATURE_1 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.Spin_Box_TEMPERATURE_1.setDecimals(2)
        self.Spin_Box_TEMPERATURE_1.setMinimum(-1000.0)
        self.Spin_Box_TEMPERATURE_1.setMaximum(100000.0)
        self.Spin_Box_TEMPERATURE_1.setObjectName("Spin_Box_TEMPERATURE_1")
        self.gridLayout_2.addWidget(self.Spin_Box_TEMPERATURE_1, 0, 3, 1, 1)
        self.Auto_Cal_Active_Box_2 = QtWidgets.QCheckBox(self.groupBox_6)
        self.Auto_Cal_Active_Box_2.setChecked(False)
        self.Auto_Cal_Active_Box_2.setObjectName("Auto_Cal_Active_Box_2")
        self.gridLayout_2.addWidget(self.Auto_Cal_Active_Box_2, 1, 5, 1, 1)
        self.Spin_Box_DLY_4 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.Spin_Box_DLY_4.setDecimals(0)
        self.Spin_Box_DLY_4.setMinimum(-1000.0)
        self.Spin_Box_DLY_4.setMaximum(100000.0)
        self.Spin_Box_DLY_4.setObjectName("Spin_Box_DLY_4")
        self.gridLayout_2.addWidget(self.Spin_Box_DLY_4, 6, 1, 1, 1)
        self.label_Dis7_4 = QtWidgets.QLabel(self.groupBox_6)
        self.label_Dis7_4.setObjectName("label_Dis7_4")
        self.gridLayout_2.addWidget(self.label_Dis7_4, 9, 0, 1, 1)
        self.Write_Flag__Box_7 = QtWidgets.QCheckBox(self.groupBox_6)
        self.Write_Flag__Box_7.setObjectName("Write_Flag__Box_7")
        self.gridLayout_2.addWidget(self.Write_Flag__Box_7, 9, 6, 1, 1)
        self.Auto_Cal_Active_Box_9 = QtWidgets.QCheckBox(self.groupBox_6)
        self.Auto_Cal_Active_Box_9.setChecked(False)
        self.Auto_Cal_Active_Box_9.setObjectName("Auto_Cal_Active_Box_9")
        self.gridLayout_2.addWidget(self.Auto_Cal_Active_Box_9, 13, 5, 1, 1)
        self.Spin_Box_DISTANCE_5 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.Spin_Box_DISTANCE_5.setDecimals(0)
        self.Spin_Box_DISTANCE_5.setMinimum(-1000.0)
        self.Spin_Box_DISTANCE_5.setMaximum(100000.0)
        self.Spin_Box_DISTANCE_5.setObjectName("Spin_Box_DISTANCE_5")
        self.gridLayout_2.addWidget(self.Spin_Box_DISTANCE_5, 7, 2, 1, 1)
        self.Write_Flag__Box_4 = QtWidgets.QCheckBox(self.groupBox_6)
        self.Write_Flag__Box_4.setObjectName("Write_Flag__Box_4")
        self.gridLayout_2.addWidget(self.Write_Flag__Box_4, 6, 6, 1, 1)
        self.Write_Flag__Box_1 = QtWidgets.QCheckBox(self.groupBox_6)
        self.Write_Flag__Box_1.setChecked(False)
        self.Write_Flag__Box_1.setObjectName("Write_Flag__Box_1")
        self.gridLayout_2.addWidget(self.Write_Flag__Box_1, 0, 6, 1, 1)
        self.Spin_Box_DLY_7 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.Spin_Box_DLY_7.setDecimals(0)
        self.Spin_Box_DLY_7.setMinimum(-1000.0)
        self.Spin_Box_DLY_7.setMaximum(100000.0)
        self.Spin_Box_DLY_7.setObjectName("Spin_Box_DLY_7")
        self.gridLayout_2.addWidget(self.Spin_Box_DLY_7, 9, 1, 1, 1)
        self.Spin_Box_TEMPERATURE_6 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.Spin_Box_TEMPERATURE_6.setDecimals(2)
        self.Spin_Box_TEMPERATURE_6.setMinimum(-1000.0)
        self.Spin_Box_TEMPERATURE_6.setMaximum(100000.0)
        self.Spin_Box_TEMPERATURE_6.setObjectName("Spin_Box_TEMPERATURE_6")
        self.gridLayout_2.addWidget(self.Spin_Box_TEMPERATURE_6, 8, 3, 1, 1)
        self.Spin_Box_TEMPERATURE_5 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.Spin_Box_TEMPERATURE_5.setDecimals(2)
        self.Spin_Box_TEMPERATURE_5.setMinimum(-1000.0)
        self.Spin_Box_TEMPERATURE_5.setMaximum(100000.0)
        self.Spin_Box_TEMPERATURE_5.setObjectName("Spin_Box_TEMPERATURE_5")
        self.gridLayout_2.addWidget(self.Spin_Box_TEMPERATURE_5, 7, 3, 1, 1)
        self.Spin_Box_DISTANCE_4 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.Spin_Box_DISTANCE_4.setDecimals(0)
        self.Spin_Box_DISTANCE_4.setMinimum(-1000.0)
        self.Spin_Box_DISTANCE_4.setMaximum(100000.0)
        self.Spin_Box_DISTANCE_4.setObjectName("Spin_Box_DISTANCE_4")
        self.gridLayout_2.addWidget(self.Spin_Box_DISTANCE_4, 6, 2, 1, 1)
        self.Write_Flag__Box_9 = QtWidgets.QCheckBox(self.groupBox_6)
        self.Write_Flag__Box_9.setObjectName("Write_Flag__Box_9")
        self.gridLayout_2.addWidget(self.Write_Flag__Box_9, 13, 6, 1, 1)
        self.Spin_Box_TEMPERATURE_9 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.Spin_Box_TEMPERATURE_9.setDecimals(2)
        self.Spin_Box_TEMPERATURE_9.setMinimum(-1000.0)
        self.Spin_Box_TEMPERATURE_9.setMaximum(100000.0)
        self.Spin_Box_TEMPERATURE_9.setObjectName("Spin_Box_TEMPERATURE_9")
        self.gridLayout_2.addWidget(self.Spin_Box_TEMPERATURE_9, 13, 3, 1, 1)
        self.Spin_Box_TEMPERATURE_7 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.Spin_Box_TEMPERATURE_7.setDecimals(2)
        self.Spin_Box_TEMPERATURE_7.setMinimum(-1000.0)
        self.Spin_Box_TEMPERATURE_7.setMaximum(100000.0)
        self.Spin_Box_TEMPERATURE_7.setObjectName("Spin_Box_TEMPERATURE_7")
        self.gridLayout_2.addWidget(self.Spin_Box_TEMPERATURE_7, 9, 3, 1, 1)
        self.Spin_Box_DLY_3 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.Spin_Box_DLY_3.setDecimals(0)
        self.Spin_Box_DLY_3.setMinimum(-1000.0)
        self.Spin_Box_DLY_3.setMaximum(100000.0)
        self.Spin_Box_DLY_3.setObjectName("Spin_Box_DLY_3")
        self.gridLayout_2.addWidget(self.Spin_Box_DLY_3, 4, 1, 1, 1)
        self.label_Dis3_4 = QtWidgets.QLabel(self.groupBox_6)
        self.label_Dis3_4.setObjectName("label_Dis3_4")
        self.gridLayout_2.addWidget(self.label_Dis3_4, 4, 0, 1, 1)
        self.Spin_Box_VOLTAGE_3 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.Spin_Box_VOLTAGE_3.setDecimals(2)
        self.Spin_Box_VOLTAGE_3.setMinimum(-1000.0)
        self.Spin_Box_VOLTAGE_3.setMaximum(100000.0)
        self.Spin_Box_VOLTAGE_3.setObjectName("Spin_Box_VOLTAGE_3")
        self.gridLayout_2.addWidget(self.Spin_Box_VOLTAGE_3, 4, 4, 1, 1)
        self.Auto_Cal_Active_Box_3 = QtWidgets.QCheckBox(self.groupBox_6)
        self.Auto_Cal_Active_Box_3.setChecked(False)
        self.Auto_Cal_Active_Box_3.setObjectName("Auto_Cal_Active_Box_3")
        self.gridLayout_2.addWidget(self.Auto_Cal_Active_Box_3, 4, 5, 1, 1)
        self.Write_Flag__Box_3 = QtWidgets.QCheckBox(self.groupBox_6)
        self.Write_Flag__Box_3.setObjectName("Write_Flag__Box_3")
        self.gridLayout_2.addWidget(self.Write_Flag__Box_3, 4, 6, 1, 1)
        self.label_Dis6_8 = QtWidgets.QLabel(self.groupBox_6)
        self.label_Dis6_8.setObjectName("label_Dis6_8")
        self.gridLayout_2.addWidget(self.label_Dis6_8, 13, 0, 1, 1)
        self.bnt_write_ANT_CAL = QtWidgets.QPushButton(self.groupBox_6)
        self.bnt_write_ANT_CAL.setObjectName("bnt_write_ANT_CAL")
        self.gridLayout_2.addWidget(self.bnt_write_ANT_CAL, 13, 7, 1, 1)
        self.bnt_read_ANT_CAL = QtWidgets.QPushButton(self.groupBox_6)
        self.bnt_read_ANT_CAL.setObjectName("bnt_read_ANT_CAL")
        self.gridLayout_2.addWidget(self.bnt_read_ANT_CAL, 10, 7, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 330, 171, 140))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_txtName = QtWidgets.QLabel(self.groupBox_3)
        self.label_txtName.setObjectName("label_txtName")
        self.horizontalLayout_6.addWidget(self.label_txtName)
        self.lineEdit_txtName = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_txtName.setInputMask("")
        self.lineEdit_txtName.setObjectName("lineEdit_txtName")
        self.horizontalLayout_6.addWidget(self.lineEdit_txtName)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_AutoSaveNum = QtWidgets.QLabel(self.groupBox_3)
        self.label_AutoSaveNum.setObjectName("label_AutoSaveNum")
        self.horizontalLayout_7.addWidget(self.label_AutoSaveNum)
        self.spinBox_AutoSaveNum = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox_AutoSaveNum.setMinimum(1)
        self.spinBox_AutoSaveNum.setMaximum(1000)
        self.spinBox_AutoSaveNum.setProperty("value", 100)
        self.spinBox_AutoSaveNum.setObjectName("spinBox_AutoSaveNum")
        self.horizontalLayout_7.addWidget(self.spinBox_AutoSaveNum)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.txt_Save = QtWidgets.QPushButton(self.groupBox_3)
        self.txt_Save.setObjectName("txt_Save")
        self.verticalLayout_4.addWidget(self.txt_Save)
        self.txt_Start = QtWidgets.QPushButton(self.groupBox_3)
        self.txt_Start.setObjectName("txt_Start")
        self.verticalLayout_4.addWidget(self.txt_Start)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(2)
        self.comboBox_air_baudrate.setCurrentIndex(2)
        self.comboBox_serial_baudrate.setCurrentIndex(7)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Target Trace App"))
        self.formGroupBox.setTitle(_translate("Form", "串口设置"))
        self.s1__lb_1.setText(_translate("Form", "串口检测："))
        self.s1__box_1.setText(_translate("Form", "检测串口"))
        self.s1__lb_2.setText(_translate("Form", "串口选择："))
        self.s1__lb_3.setText(_translate("Form", "波特率："))
        self.s1__box_3.setCurrentText(_translate("Form", "115200"))
        self.s1__box_3.setItemText(0, _translate("Form", "115200"))
        self.s1__box_3.setItemText(1, _translate("Form", "9600"))
        self.s1__box_3.setItemText(2, _translate("Form", "2400"))
        self.s1__box_3.setItemText(3, _translate("Form", "4800"))
        self.s1__box_3.setItemText(4, _translate("Form", "14400"))
        self.s1__box_3.setItemText(5, _translate("Form", "19200"))
        self.s1__box_3.setItemText(6, _translate("Form", "38400"))
        self.s1__box_3.setItemText(7, _translate("Form", "57600"))
        self.s1__box_3.setItemText(8, _translate("Form", "76800"))
        self.s1__box_3.setItemText(9, _translate("Form", "12800"))
        self.s1__box_3.setItemText(10, _translate("Form", "460800"))
        self.s1__box_3.setItemText(11, _translate("Form", "230400"))
        self.s1__lb_4.setText(_translate("Form", "数据位："))
        self.s1__box_4.setItemText(0, _translate("Form", "8"))
        self.s1__box_4.setItemText(1, _translate("Form", "7"))
        self.s1__box_4.setItemText(2, _translate("Form", "6"))
        self.s1__box_4.setItemText(3, _translate("Form", "5"))
        self.s1__lb_5.setText(_translate("Form", "校验位："))
        self.s1__box_5.setItemText(0, _translate("Form", "N"))
        self.s1__lb_6.setText(_translate("Form", "停止位："))
        self.s1__box_6.setItemText(0, _translate("Form", "1"))
        self.open_button.setText(_translate("Form", "打开串口"))
        self.close_button.setText(_translate("Form", "关闭串口"))
        self.label.setText(_translate("Form", "已接收："))
        self.label_2.setText(_translate("Form", "已发送："))
        self.btn_connect_device.setText(_translate("Form", "连接设备"))
        self.groupBox_2.setTitle(_translate("Form", "设备参数"))
        self.label_modbus_addr.setText(_translate("Form", "Modbus地址"))
        self.label_device_ID.setText(_translate("Form", "基站编号(行,列)"))
        self.comboBox_device_ID.setItemText(0, _translate("Form", "1,1(A)"))
        self.comboBox_device_ID.setItemText(1, _translate("Form", "1,2(B)"))
        self.comboBox_device_ID.setItemText(2, _translate("Form", "1,3(C)"))
        self.comboBox_device_ID.setItemText(3, _translate("Form", "2,1(D)"))
        self.comboBox_device_ID.setItemText(4, _translate("Form", "3,1(E)"))
        self.comboBox_device_ID.setItemText(5, _translate("Form", "3,3(F)"))
        self.comboBox_device_ID.setItemText(6, _translate("Form", "2,2(G)"))
        self.comboBox_device_ID.setItemText(7, _translate("Form", "2,3(H)"))
        self.comboBox_device_ID.setItemText(8, _translate("Form", "3,2(I)"))
        self.comboBox_device_ID.setItemText(9, _translate("Form", "Debug_AP"))
        self.label_Antdelay.setText(_translate("Form", "天线延迟"))
        self.label_reference_dis.setText(_translate("Form", "自校准参考距离(cm)"))
        self.btn_auto_calibration.setText(_translate("Form", "自动校准"))
        self.label_air_baudrate.setText(_translate("Form", "空中码率"))
        self.comboBox_air_baudrate.setItemText(0, _translate("Form", "110kbps"))
        self.comboBox_air_baudrate.setItemText(1, _translate("Form", "850kbps"))
        self.comboBox_air_baudrate.setItemText(2, _translate("Form", "6.8Mbps"))
        self.label_serial_baudrate.setText(_translate("Form", "串口码率"))
        self.comboBox_serial_baudrate.setItemText(0, _translate("Form", "4800"))
        self.comboBox_serial_baudrate.setItemText(1, _translate("Form", "9600"))
        self.comboBox_serial_baudrate.setItemText(2, _translate("Form", "14400"))
        self.comboBox_serial_baudrate.setItemText(3, _translate("Form", "19200"))
        self.comboBox_serial_baudrate.setItemText(4, _translate("Form", "38400"))
        self.comboBox_serial_baudrate.setItemText(5, _translate("Form", "56000"))
        self.comboBox_serial_baudrate.setItemText(6, _translate("Form", "57600"))
        self.comboBox_serial_baudrate.setItemText(7, _translate("Form", "115200"))
        self.comboBox_serial_baudrate.setItemText(8, _translate("Form", "128000"))
        self.comboBox_serial_baudrate.setItemText(9, _translate("Form", "256000"))
        self.label_Device_Mode.setText(_translate("Form", "标签/基站"))
        self.comboBox_Device_Mode.setItemText(0, _translate("Form", "标签"))
        self.comboBox_Device_Mode.setItemText(1, _translate("Form", "基站"))
        self.label_3.setText(_translate("Form", "基站坐标(x,y,z)"))
        self.btn_write_para.setText(_translate("Form", "设定参数"))
        self.btn_read_para.setText(_translate("Form", "读取参数"))
        self.s2__clear_button.setText(_translate("Form", "清除"))
        self.hex_receive.setText(_translate("Form", "Hex接收"))
        self.hex_send.setText(_translate("Form", "Hex发送"))
        self.verticalGroupBox_2.setTitle(_translate("Form", "发送区"))
        self.s3__send_text.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">123456</p></body></html>"))
        self.lineEdit_3.setText(_translate("Form", "1000"))
        self.timer_send_cb.setText(_translate("Form", "定时发送"))
        self.dw.setText(_translate("Form", "ms/次"))
        self.verticalGroupBox.setTitle(_translate("Form", "接受区"))
        self.s3__clear_button.setText(_translate("Form", "清除"))
        self.s3__send_button.setText(_translate("Form", "发送"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "单模块调试"))
        self.groupBox.setTitle(_translate("Form", "标签坐标显示（x,y,z）"))
        self.label_Tatrget_x.setText(_translate("Form", "x"))
        self.label_Tatrget_y.setText(_translate("Form", "y"))
        self.label_Tatrget_z.setText(_translate("Form", "z"))
        self.Trace_Start.setText(_translate("Form", "开始绘图"))
        self.Trace_Stop.setText(_translate("Form", "停止"))
        self.groupBox_4.setTitle(_translate("Form", "采样距离显示"))
        self.label_Dis1.setText(_translate("Form", "DisA"))
        self.label_Dis2.setText(_translate("Form", "DisB"))
        self.label_Dis3.setText(_translate("Form", "DisC"))
        self.label_Dis4.setText(_translate("Form", "DisD"))
        self.label_Dis5.setText(_translate("Form", "DisE"))
        self.label_Dis6.setText(_translate("Form", "DisF"))
        self.label_Dis7.setText(_translate("Form", "DisG"))
        self.label_Dis8.setText(_translate("Form", "DisH"))
        self.label_Dis6_2.setText(_translate("Form", "DisI"))
        self.groupBox_AP_Position.setTitle(_translate("Form", "基站群的绘图坐标（x,y,z）"))
        self.label_x1.setText(_translate("Form", "AP1_x(1,1)"))
        self.label_y1.setText(_translate("Form", "AP1_y"))
        self.label_z1.setText(_translate("Form", "AP1_z"))
        self.label_x2.setText(_translate("Form", "AP2_x(1,2)"))
        self.label_y2.setText(_translate("Form", "AP2_y"))
        self.label_z2.setText(_translate("Form", "AP2_z"))
        self.label_x3.setText(_translate("Form", "AP3_x(1,3)"))
        self.label_y3.setText(_translate("Form", "AP3_y"))
        self.label_z3.setText(_translate("Form", "AP3_z"))
        self.label_x4.setText(_translate("Form", "AP4_x(2,1)"))
        self.label_y4.setText(_translate("Form", "AP4_y"))
        self.label_z4.setText(_translate("Form", "AP4_z"))
        self.label_x5.setText(_translate("Form", "AP5_x(3,1)"))
        self.label_y5.setText(_translate("Form", "AP5_y"))
        self.label_z5.setText(_translate("Form", "AP5_z"))
        self.label_x6.setText(_translate("Form", "AP6_x(3,3)"))
        self.label_y6.setText(_translate("Form", "AP6_y"))
        self.label_z6.setText(_translate("Form", "AP6_z"))
        self.label_x7.setText(_translate("Form", "AP7_x(2,2)"))
        self.label_y7.setText(_translate("Form", "AP7_y"))
        self.label_z7.setText(_translate("Form", "AP7_z"))
        self.label_x8.setText(_translate("Form", "AP8_x(2,3)"))
        self.label_y8.setText(_translate("Form", "AP8_y"))
        self.label_z8.setText(_translate("Form", "AP8_z"))
        self.label_x9.setText(_translate("Form", "AP9_x(3,2)"))
        self.label_y9.setText(_translate("Form", "AP9_y"))
        self.label_z9.setText(_translate("Form", "AP9_z"))
        item = self.tableWidget_monitor.verticalHeaderItem(0)
        item.setText(_translate("Form", "A "))
        item = self.tableWidget_monitor.verticalHeaderItem(1)
        item.setText(_translate("Form", "B"))
        item = self.tableWidget_monitor.verticalHeaderItem(2)
        item.setText(_translate("Form", "C"))
        item = self.tableWidget_monitor.verticalHeaderItem(3)
        item.setText(_translate("Form", "D"))
        item = self.tableWidget_monitor.verticalHeaderItem(4)
        item.setText(_translate("Form", "E"))
        item = self.tableWidget_monitor.verticalHeaderItem(5)
        item.setText(_translate("Form", "F"))
        item = self.tableWidget_monitor.verticalHeaderItem(6)
        item.setText(_translate("Form", "G"))
        item = self.tableWidget_monitor.verticalHeaderItem(7)
        item.setText(_translate("Form", "H"))
        item = self.tableWidget_monitor.verticalHeaderItem(8)
        item.setText(_translate("Form", "I"))
        item = self.tableWidget_monitor.horizontalHeaderItem(0)
        item.setText(_translate("Form", "采样距离"))
        item = self.tableWidget_monitor.horizontalHeaderItem(1)
        item.setText(_translate("Form", "参考距离"))
        item = self.tableWidget_monitor.horizontalHeaderItem(2)
        item.setText(_translate("Form", "天线延迟"))
        item = self.tableWidget_monitor.horizontalHeaderItem(3)
        item.setText(_translate("Form", "温度"))
        item = self.tableWidget_monitor.horizontalHeaderItem(4)
        item.setText(_translate("Form", "电压"))
        __sortingEnabled = self.tableWidget_monitor.isSortingEnabled()
        self.tableWidget_monitor.setSortingEnabled(False)
        item = self.tableWidget_monitor.item(0, 0)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_monitor.item(0, 1)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_monitor.item(0, 2)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_monitor.item(0, 3)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_monitor.item(0, 4)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_monitor.item(1, 0)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_monitor.item(1, 1)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_monitor.item(1, 2)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_monitor.item(1, 3)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_monitor.item(1, 4)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_monitor.item(2, 0)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_monitor.item(2, 1)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_monitor.item(2, 2)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_monitor.item(2, 3)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_monitor.item(2, 4)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_monitor.item(3, 0)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_monitor.item(3, 1)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_monitor.item(3, 2)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_monitor.item(3, 3)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_monitor.item(3, 4)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_monitor.item(4, 0)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_monitor.item(4, 1)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_monitor.item(4, 2)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_monitor.item(4, 3)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_monitor.item(4, 4)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_monitor.item(5, 0)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_monitor.item(5, 1)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_monitor.item(5, 2)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_monitor.item(5, 3)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_monitor.item(5, 4)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_monitor.item(6, 0)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_monitor.item(6, 1)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_monitor.item(6, 2)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_monitor.item(6, 3)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_monitor.item(6, 4)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_monitor.item(7, 0)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_monitor.item(7, 1)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_monitor.item(7, 2)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_monitor.item(7, 3)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_monitor.item(7, 4)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_monitor.item(8, 0)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_monitor.item(8, 1)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_monitor.item(8, 2)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_monitor.item(8, 3)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget_monitor.item(8, 4)
        item.setText(_translate("Form", "0"))
        self.tableWidget_monitor.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "基站群调试"))
        self.groupBox_6.setTitle(_translate("Form", "天线延迟-参考距离-参考温度-参考电压"))
        self.Auto_Cal_Active_Box_6.setText(_translate("Form", "校准"))
        self.label_Dis1_4.setText(_translate("Form", "A"))
        self.label_Dis4_4.setText(_translate("Form", "D"))
        self.label_Dis6_7.setText(_translate("Form", "F"))
        self.Write_Flag__Box_2.setText(_translate("Form", "B"))
        self.Write_Flag__Box_8.setText(_translate("Form", "H"))
        self.label_Dis8_4.setText(_translate("Form", "H"))
        self.label_Dis5_4.setText(_translate("Form", "E"))
        self.Auto_Cal_Active_Box_5.setText(_translate("Form", "校准"))
        self.Auto_Cal_Active_Box_8.setText(_translate("Form", "校准"))
        self.Auto_Cal_Active_Box_7.setText(_translate("Form", "校准"))
        self.label_Dis2_4.setText(_translate("Form", "B"))
        self.Write_Flag__Box_5.setText(_translate("Form", "E"))
        self.Auto_Cal_Active_Box_1.setText(_translate("Form", "校准"))
        self.Write_Flag__Box_6.setText(_translate("Form", "F"))
        self.Auto_Cal_Active_Box_4.setText(_translate("Form", "校准"))
        self.Auto_Cal_Active_Box_2.setText(_translate("Form", "校准"))
        self.label_Dis7_4.setText(_translate("Form", "G"))
        self.Write_Flag__Box_7.setText(_translate("Form", "G"))
        self.Auto_Cal_Active_Box_9.setText(_translate("Form", "校准"))
        self.Write_Flag__Box_4.setText(_translate("Form", "D"))
        self.Write_Flag__Box_1.setText(_translate("Form", "A"))
        self.Write_Flag__Box_9.setText(_translate("Form", "I"))
        self.label_Dis3_4.setText(_translate("Form", "C"))
        self.Auto_Cal_Active_Box_3.setText(_translate("Form", "校准"))
        self.Write_Flag__Box_3.setText(_translate("Form", "C"))
        self.label_Dis6_8.setText(_translate("Form", "I"))
        self.bnt_write_ANT_CAL.setText(_translate("Form", "write"))
        self.bnt_read_ANT_CAL.setText(_translate("Form", "read"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "天线校准"))
        self.groupBox_3.setTitle(_translate("Form", "采样数据保存"))
        self.label_txtName.setText(_translate("Form", "文件名"))
        self.lineEdit_txtName.setText(_translate("Form", "注意：同名文件会被覆盖"))
        self.label_AutoSaveNum.setText(_translate("Form", "自动保存上限"))
        self.txt_Save.setText(_translate("Form", "保存"))
        self.txt_Start.setText(_translate("Form", "开始记录"))
